### ISSUE TITLE
Plots are not rendered properly when there is a single value

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc-render#106]
https://user-images.githubusercontent.com/3659196/208209132-1adef38e-9314-4808-ae00-1aab5ab494b1.mov

VS Code:

<img width="1134" alt="Screen Shot 2022-12-16 at 3 47 57 PM" src="https://user-images.githubusercontent.com/3659196/208209233-20fd690c-e0e5-42b7-8a4e-4ac9e3c85308.png">

**Comment by dberenbaum** [comment]
I get the current behavior is confusing since it looks like plots are broken, but can we hide these rather than "fix" them to show the single point? It still looks pretty bad even when "working" to me. Not sure where it would be best to handle this. 

Can/should dvc-render never render plots with only one point and warn/error instead?

It could also be handled in dvclive. Some options:
1. Go back to not writing the tsv until step 1.
2. Only write to tsv files during `next_step`.
3. Drop the tsv during `live.end` if no step.
4. Exclude plots metrics when writing dvc.yaml in step 0.

**Comment by shcheklein** [comment]
Hmm, I'm not sure I understand why should we be disabling them tbh.

- If I'm live tracking something it's really good to see something asap, otherwise there will be a delay (sometimes minutes or hours before something comes up). It is encouraging for me to see the first value, after the first epoch asap. Also, who knows I might even see something from it.
- I think we are becoming opinionated then. We can't predict (and probably should not) how ppl would utilize plots.

My 2cs - I think we should probably fix it, and render in a way it's expected to be rendered.

**Comment by daavoo** [comment]
I haven't investigated in depth but I think this is a limitation of vega itself

**Comment by dberenbaum** [comment]
> * If I'm live tracking something it's really good to see something asap, otherwise there will be a delay (sometimes minutes or hours before something comes up). It is encouraging for me to see the first value, after the first epoch asap. Also, who knows I might even see something from it.

Okay, didn't realize this was for live updates. I was thinking these were the final plots, in which case it's hard for me to imagine they will be useful, but I see what you mean for live updates.
