### ISSUE TITLE
`plots`: Add bar chart template

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc-render#8]
- https://vega.github.io/vega-lite/examples/bar.html

**Comment by tibor-mach** [comment]
This is quite a trivial modification of the default `simple.json` template (sorted by size, I am mostly using it for visualising feature importances)

```
{
    "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "title": "<DVC_METRIC_TITLE>",
    "width": 300,
    "height": 300,
    "mark": {
        "type": "bar"
    },
    "encoding": {
        "x": {
            "field": "<DVC_METRIC_X>",
            "type": "quantitative",
            "title": "<DVC_METRIC_X_LABEL>",
            "scale": {
                "zero": false
            }
        },
        "y": {
            "field": "<DVC_METRIC_Y>",
            "type": "nominal",
            "title": "<DVC_METRIC_Y_LABEL>",
            "sort":"-x"
        },
        "color": {
            "field": "rev",
            "type": "nominal"
        }
    }
}
```
But there is a problem with calling `dvc plots diff`, since it simply sums the values in each column, producing nonsense. Is there a simple way to make diff work like it does with confusion matrices (simply putting the old and new next to each other)? Or an even better - the `diff` could produce a grouped bar chart kind of like [this one](https://vega.github.io/vega-lite/examples/bar_grouped.html) (only horizontal).

**Comment by daavoo** [comment]
@tibor-mach You can use https://vega.github.io/vega-lite/docs/encoding.html#positon-offset :


```diff
{
    "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "title": "<DVC_METRIC_TITLE>",
    "width": 300,
    "height": 300,
    "mark": {
        "type": "bar"
    },
    "encoding": {
        "x": {
            "field": "<DVC_METRIC_X>",
            "type": "quantitative",
            "title": "<DVC_METRIC_X_LABEL>",
            "scale": {
                "zero": false
            }
        },
        "y": {
            "field": "<DVC_METRIC_Y>",
            "type": "nominal",
            "title": "<DVC_METRIC_Y_LABEL>",
            "sort":"-x"
        },
+       "yOffset": {"field": "rev"},
        "color": {
            "field": "rev",
            "type": "nominal"
        }
    }
}
```

**Comment by tibor-mach** [comment]
Hmm, this works but in a curious way. When opened in the VS code dvc extension it works just as intended. When opened in the browser (firefox) via `dvc plots diff --open` it does not actually do the offset. It might be an issue with firefox I guess...

VS Code extension: 
![image](https://user-images.githubusercontent.com/56956998/176216874-e2251665-b980-43d7-8742-5b3d7a2bcc57.png)

Firefox:
![image](https://user-images.githubusercontent.com/56956998/176217076-626b8eac-597d-41c1-85d4-4ad0b3140810.png)

**Comment by tibor-mach** [comment]
And Chromium seems to render it the same way as Firefox...so it is unlikely a specific problem with one browser. I now wonder why it actually does work in VS Code :)

**Comment by tibor-mach** [comment]
Heh, yeah I was just going to say that the issue is with the version of vega. The error message goes away with the change in schema, but firefox still renders it wrong.

More precisely, the problem is with the version of `vega-lite`. If I change this:

```
    <script src="https://cdn.jsdelivr.net/npm/vega@5.20.2"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@5.1.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.18.2"></script>
```

to this:

```
    <script src="https://cdn.jsdelivr.net/npm/vega@5.20.2"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@5.2.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.18.2"></script>
```
then it works as intended. The validation schema is just for validation, dvc still renders the `html` with the same vega versions (but it would be good to bump it to v5 even for the default templates I guess).

So the fix is to have dvc use `vega-lite v5.2.0` instead of `vega-lite v5.1.0`

**Comment by tibor-mach** [comment]
@daavoo Can we add (some version of) this? The template is a bit specific with the ordering (but that is useful exactly for the usecase of feature importance graphs). I guess the best thing would be to just have bar and make it configurable via commands.

But a more pressing thing is the vega-lite version, that is basically a bug (except that it does not manifest with the current default templates). The fix seems easy enough but I am not sure where the vega-lite version is specified (and I also understand that this is maybe not a part of dvc itself?)

**Comment by tibor-mach** [comment]
It looks like there are still some problems with CML reports. With the latest version of DVC, everything works fine both in the VS code extension and in the browser, but for some reason this is not true of CML when I create plots within a github workflow and publishing them with cml. I use the following code

@daavoo 
```
dvc plots diff $GITHUB_BASE_REF $GITHUB_HEAD_REF \
    --target <my_bar_plot.csv> \
    --show-vega > vega.json
vl2svg vega.json > plot.svg
cml publish --md plot.svg >> report.md
```
When I do the same locally (without cml) with dvc 5.12.0 and vega-lite 5.2.0 it works just fine and the resulting svg is rendered correctly.

But with CML in a GitHub workflow it does not and I get the errors indicating that the xOffset is not available (which suggests older versions of vega-lite):

```
WARN xOffset-encoding is dropped as xOffset is not a valid encoding channel.
```
I use the `iterative/setup-cml@v1` action to set up cml. And in fact, the problem seems to be here:

https://github.com/iterative/setup-cml/blob/7eecee79650503f8624b7012b89d27bef4f7de60/src/utils.js#L51

I am going to create an issue in the setup-cml action, should be easy to solve (provided this is the only problem, but it is likely).

**Comment by daavoo** [comment]
> @daavoo Can we add (some version of) this? The template is a bit specific with the ordering (but that is useful exactly for the usecase of feature importance graphs). I guess the best thing would be to just have bar and make it configurable via commands.

Sure thing. You already did pretty much all the job. Would you be willing to contribute it? 

You would need to add a new class to `dvc_render/vega_templates.py` and expose it in the [`TEMPLATES` list](https://github.com/iterative/dvc-render/blob/70e2da2e799fc3942d243fec6df359302d9a6e12/src/dvc_render/vega_templates.py#L651-L658 ).

Regarding the sorting, I think we could just add 2 separate templates one with sorting and one without.

**Comment by Robbie-Palmer** [comment]
Now that #67 has merged will the bar chart template soon become available in a `dvc` release?

**Comment by daavoo** [comment]
> Now that https://github.com/iterative/dvc-render/pull/67 has merged will the bar chart template soon become available in a dvc release?

Yes, next release will contain the template as part of the defaults
